development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: weighin_rails_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: weighin_rails_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: weighin_rails_production
